import * as dotenv from 'dotenv';

dotenv.config();

const {
  FASST_OASIS_MS_OAUTH_ENDPOINT,
  FASST_OASIS_MS_OAUTH_CLIENT_ID,
  FASST_OASIS_MS_OAUTH_CLIENT_SECRET,
  FASST_OASIS_MS_OAUTH_RESOURCE,
  FAST_OASIS_MS_OAUTH_GRANT_TYPE,
  FASTT_OASIS_BASE_URL,
} = process.env;

if (
  !FASST_OASIS_MS_OAUTH_ENDPOINT ||
  !FASST_OASIS_MS_OAUTH_CLIENT_ID ||
  !FASST_OASIS_MS_OAUTH_CLIENT_SECRET ||
  !FASST_OASIS_MS_OAUTH_RESOURCE ||
  !FAST_OASIS_MS_OAUTH_GRANT_TYPE ||
  !FASTT_OASIS_BASE_URL
) {
  throw new Error(
    'OASIS_MS_OAUTH_ENDPOINT, OASIS_MS_OAUTH_CLIENT_ID, OASIS_MS_OAUTH_CLIENT_SECRET, OASIS_MS_OAUTH_RESOURCE, FAST_OASIS_MS_OAUTH_GRANT_TYPE, and FASTT_OASIS_BASE_URL env variables must be set',
  );
}

export const oasisConstants = {
  oauthEndpoint: FASST_OASIS_MS_OAUTH_ENDPOINT,
  oauthClientId: FASST_OASIS_MS_OAUTH_CLIENT_ID,
  oauthClientSecret: FASST_OASIS_MS_OAUTH_CLIENT_SECRET,
  oauthResource: FASST_OASIS_MS_OAUTH_RESOURCE,
  oauthGrantType: FAST_OASIS_MS_OAUTH_GRANT_TYPE,
  oasisBaseUrl: FASTT_OASIS_BASE_URL,
};
